# Generated by Django 3.2.15 on 2024-01-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_class',
            field=models.CharField(choices=[('general', 'General'), ('sleeper', 'Sleeper'), ('3a', '3A'), ('2a', '2A'), ('first_class', 'First Class')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
