# Generated by Django 3.2.15 on 2023-12-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='days_of_the_week',
            field=models.CharField(blank=True, help_text='Comma-separated list of days', max_length=50),
        ),
    ]
